# Generated by Django 5.1.4 on 2026-08-04 05:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_time_hours', models.PositiveIntegerField(help_text='Hours from acceptance to delivery.')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=12)),
                ('is_boosted', models.BooleanField(default=False, help_text='Paid placement at the top of the list.')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_boosted', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('subject', models.CharField(choices=[('business', 'Business & Management'), ('nursing', 'Nursing & Healthcare'), ('law', 'Law'), ('psychology', 'Psychology'), ('engineering', 'Engineering'), ('it', 'IT & Computer Science'), ('literature', 'Literature & English'), ('history', 'History'), ('economics', 'Economics & Finance'), ('education', 'Education'), ('science', 'Natural Sciences'), ('marketing', 'Marketing & Copywriting'), ('other', 'Other')], default='other', max_length=30)),
                ('order_type', models.CharField(choices=[('writing', 'Writing'), ('humanization', 'AI humanization / rewriting')], db_index=True, default='writing', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open_for_bids', 'Open for bids'), ('bid_accepted', 'Bid accepted — awaiting funding'), ('escrowed', 'Funded / in escrow'), ('in_progress', 'In progress'), ('submitted', 'Submitted for review'), ('in_revision', 'In revision'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('canceled', 'Canceled')], db_index=True, default='draft', max_length=20)),
                ('deadline', models.DateTimeField()),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('word_count', models.PositiveIntegerField(blank=True, help_text='Auto-parsed for humanization orders; drives the locked price.', null=True)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('review_deadline', models.DateTimeField(blank=True, help_text='Auto-approve fires after this.', null=True)),
                ('revision_count', models.PositiveIntegerField(default=0)),
                ('was_late', models.BooleanField(default=False)),
                ('accepted_bid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_order', to='orders.bid')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('late_delivery', 'Late delivery'), ('quality', 'Quality failure'), ('plagiarism', 'Plagiarism / AI content'), ('contact_leak', 'Off-platform contact attempt')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_refund_portion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_portion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('days_late', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_waived', models.BooleanField(default=False)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='disputes/%Y/%m/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under review'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=15)),
                ('resolution', models.CharField(blank=True, choices=[('full_release', 'Full release to writer'), ('partial_release', 'Partial release + partial refund'), ('full_refund', 'Full refund to client')], max_length=20)),
                ('writer_share_percent', models.PositiveSmallIntegerField(default=0, help_text='Percent of escrow released to the writer on partial resolution.')),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='deliverables/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('plagiarism_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_content_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gptzero_report_url', models.URLField(blank=True)),
                ('scan_status', models.CharField(choices=[('pending', 'Scan pending'), ('running', 'Scan running'), ('done', 'Scan complete'), ('failed', 'Scan failed'), ('skipped', 'Scan skipped')], default='pending', max_length=10)),
                ('scan_error', models.CharField(blank=True, max_length=255)),
                ('flagged', models.BooleanField(db_index=True, default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=255)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='orders.order')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='orders.order'),
        ),
        migrations.CreateModel(
            name='OrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='order_attachments/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orders.order')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('reply', models.TextField(blank=True, help_text='One short response from the reviewee.')),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type', 'status'], name='orders_orde_order_t_1378c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(fields=('order', 'writer'), name='unique_bid_per_writer_order'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('order', 'reviewer'), name='one_review_per_order_per_reviewer'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_between_1_and_5'),
        ),
    ]
