# Generated by Django 5.1.4 on 2026-08-04 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('document', models.FileField(upload_to='check_requests/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('word_count', models.PositiveIntegerField(blank=True, null=True)),
                ('report_types', models.JSONField(default=list, help_text='List of ReportType values.')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=12)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('waived', 'Waived')], default='unpaid', max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(blank=True, help_text='Null for anonymous visitors.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('ai_content', 'AI content detection'), ('plagiarism', 'Plagiarism scan'), ('turnitin', 'Turnitin report'), ('similarity_links', 'Similarity / source links')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='check_reports/%Y/%m/')),
                ('report_url', models.URLField(blank=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Headline percentage.', max_digits=5, null=True)),
                ('summary', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_reports_processed', to=settings.AUTH_USER_MODEL)),
                ('check_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='checks.checkrequest')),
            ],
            options={
                'ordering': ['report_type'],
                'constraints': [models.UniqueConstraint(fields=('check_request', 'report_type'), name='one_report_per_type_per_request')],
            },
        ),
    ]
